### ISSUE TITLE
Addition of details to Index YML

### ISSUE THREAD

**Issue by AbhijithGanesh** [dokc/Helm-Charts#1]
Details for the Index YML needs to be added, it must have everything from the command to its functionality, you can refer the [prometheus](https://prometheus-community.github.io/helm-charts/) website for context and go to their `gh`-pages` branch to get data to work on. The index.yaml has ample data related to versioning and content, one can use those fields to generate a website like theirs. The helm chart requires more detailing.

**Comment by AbhijithGanesh** [comment]
Probably the readme needs to be improvized as well. I will do the needed for the same.

**Comment by Anosh21** [comment]
Hey @AbhijithGanesh I would like to work with you on this issue.

**Comment by AbhijithGanesh** [comment]
Solved using #6

**Comment by AbhijithGanesh** [comment]
Sorry @Anosh21 This was an internal PR as I was setting the helm-chart up , it wasn't open for contribution , There wasn't enough references, I built the chart and had to define it.
