### ISSUE TITLE
[FEAT]: Update version number for Package

### ISSUE THREAD

**Issue by AbhijithGanesh** [dokc/Helm-Charts#12]
The latest package `0.1.1` was pushed into the repository in `packages`, One needs to change the `index.yaml` for package-management reasons. It will reflect on hour cloud provider (GitHub and ArtifactHub) links

[Index.YAML](https://github.com/dokc/Helm-Charts/blob/8efaa6418210bc42811d9daa40d940e5bed1e57f/index.yaml#L9)

**Comment by urvishajain** [comment]
Would be great if you can assign it to me.

**Comment by ManasviGoyal** [comment]
Can I work on this?

**Comment by ManasviGoyal** [comment]
@AbhijithGanesh please check
